# app/schemas/__init__.py

"""
Aggregate imports for schemas to allow easy access like from app.schemas import SomeSchema
"""

from .user import (
    UserRole,
    PlatformUserRole,
    PasswordChangeRequest,
    ForgotPasswordRequest,
    PasswordResetRequest,
    PasswordChangeResponse,
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserLogin,
    Token,
    TokenData,
    PlatformUserBase,
    PlatformUserCreate,
    PlatformUserUpdate,
    PlatformUserInDB,
    OTPRequest,
    OTPVerifyRequest,
    OTPResponse,
)

from .organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationInDB,
    OrganizationLicenseCreate,
    OrganizationLicenseResponse
)

from .organization_settings import (
    OrganizationSettingsBase,
    OrganizationSettingsCreate,
    OrganizationSettingsUpdate,
    OrganizationSettingsInDB,
    OrganizationSettingsResponse
)

from .company import (
    CompanyBase,
    CompanyCreate,
    CompanyUpdate,
    CompanyInDB,
    CompanyResponse,
    CompanyListResponse,
    CompanyValidationError,
    CompanyErrorResponse,
    CompanyBulkImportResponse
)

from .vouchers import (
    VoucherItemBase, VoucherItemWithTax, VoucherBase,
    PurchaseVoucherItemCreate, PurchaseVoucherItemInDB,
    PurchaseVoucherCreate, PurchaseVoucherUpdate, PurchaseVoucherInDB,
    SalesVoucherItemCreate, SalesVoucherItemInDB,
    SalesVoucherCreate, SalesVoucherUpdate, SalesVoucherInDB,
    PurchaseOrderItemCreate, PurchaseOrderItemInDB,
    PurchaseOrderCreate, PurchaseOrderUpdate, PurchaseOrderInDB,
    SalesOrderItemCreate, SalesOrderItemInDB,
    SalesOrderCreate, SalesOrderUpdate, SalesOrderInDB,
    GRNItemCreate, GRNItemInDB, GRNCreate, GRNUpdate, GRNInDB,
    DeliveryChallanItemCreate, DeliveryChallanItemInDB,
    DeliveryChallanCreate, DeliveryChallanUpdate, DeliveryChallanInDB,
    ProformaInvoiceItemCreate, ProformaInvoiceItemInDB,
    ProformaInvoiceCreate, ProformaInvoiceUpdate, ProformaInvoiceInDB,
    QuotationItemCreate, QuotationItemInDB,
    QuotationCreate, QuotationUpdate, QuotationInDB
)

from .base import (
    OrganizationStatus,
    PlanType,
    VendorBase,
    VendorCreate,
    VendorUpdate,
    VendorInDB,
    CustomerBase,
    CustomerCreate,
    CustomerUpdate,
    CustomerInDB,
    ProductBase,
    ProductCreate,
    ProductUpdate,
    ProductInDB,
    StockBase,
    StockCreate,
    StockUpdate,
    StockInDB,
    BulkStockRequest,
    EmailNotificationBase,
    EmailNotificationCreate,
    EmailNotificationInDB,
    PaymentTermBase,
    PaymentTermCreate,
    PaymentTermUpdate,
    PaymentTermInDB,
    BulkImportResponse,
    BulkImportError,
    DetailedBulkImportResponse,
    NotificationTemplateBase,
    NotificationTemplateCreate,
    NotificationTemplateUpdate,
    NotificationTemplateInDB,
    NotificationLogBase,
    NotificationLogCreate,
    NotificationLogInDB,
    NotificationPreferenceBase,
    NotificationPreferenceCreate,
    NotificationPreferenceUpdate,
    NotificationPreferenceInDB,
    BulkNotificationRequest,
    NotificationSendRequest,
    NotificationSendResponse,
    BulkNotificationResponse
)

__all__ = [
    # User schemas
    "UserRole",
    "PlatformUserRole",
    "PasswordChangeRequest",
    "ForgotPasswordRequest",
    "PasswordResetRequest",
    "PasswordChangeResponse",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserLogin",
    "Token",
    "TokenData",
    "PlatformUserBase",
    "PlatformUserCreate",
    "PlatformUserUpdate",
    "PlatformUserInDB",
    "OTPRequest",
    "OTPVerifyRequest",
    "OTPResponse",
    
    # Organization schemas
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationInDB",
    "OrganizationLicenseCreate",
    "OrganizationLicenseResponse",
    
    # Company schemas
    "CompanyBase",
    "CompanyCreate",
    "CompanyUpdate",
    "CompanyInDB",
    "CompanyResponse",
    "CompanyListResponse",
    "CompanyValidationError",
    "CompanyErrorResponse",
    "CompanyBulkImportResponse",
    
    # Voucher schemas
    "VoucherItemBase", "VoucherItemWithTax", "VoucherBase",
    "PurchaseVoucherItemCreate", "PurchaseVoucherItemInDB",
    "PurchaseVoucherCreate", "PurchaseVoucherUpdate", "PurchaseVoucherInDB",
    "SalesVoucherItemCreate", "SalesVoucherItemInDB",
    "SalesVoucherCreate", "SalesVoucherUpdate", "SalesVoucherInDB",
    "PurchaseOrderItemCreate", "PurchaseOrderItemInDB",
    "PurchaseOrderCreate", "PurchaseOrderUpdate", "PurchaseOrderInDB",
    "SalesOrderItemCreate", "SalesOrderItemInDB",
    "SalesOrderCreate", "SalesOrderUpdate", "SalesOrderInDB",
    "GRNItemCreate", "GRNItemInDB", "GRNCreate", "GRNUpdate", "GRNInDB",
    "DeliveryChallanItemCreate", "DeliveryChallanItemInDB",
    "DeliveryChallanCreate", "DeliveryChallanUpdate", "DeliveryChallanInDB",
    "ProformaInvoiceItemCreate", "ProformaInvoiceItemInDB",
    "ProformaInvoiceCreate", "ProformaInvoiceUpdate", "ProformaInvoiceInDB",
    "QuotationItemCreate", "QuotationItemInDB",
    "QuotationCreate", "QuotationUpdate", "QuotationInDB",

    # Base schemas
    "OrganizationStatus",
    "PlanType",
    "VendorBase",
    "VendorCreate",
    "VendorUpdate",
    "VendorInDB",
    "CustomerBase",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerInDB",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductInDB",
    "StockBase",
    "StockCreate",
    "StockUpdate",
    "StockInDB",
    "BulkStockRequest",
    "EmailNotificationBase",
    "EmailNotificationCreate",
    "EmailNotificationInDB",
    "PaymentTermBase",
    "PaymentTermCreate",
    "PaymentTermUpdate",
    "PaymentTermInDB",
    "BulkImportResponse",
    "BulkImportError",
    "DetailedBulkImportResponse",
    "NotificationTemplateBase",
    "NotificationTemplateCreate",
    "NotificationTemplateUpdate",
    "NotificationTemplateInDB",
    "NotificationLogBase",
    "NotificationLogCreate",
    "NotificationLogInDB",
    "NotificationPreferenceBase",
    "NotificationPreferenceCreate",
    "NotificationPreferenceUpdate",
    "NotificationPreferenceInDB",
    "BulkNotificationRequest",
    "NotificationSendRequest",
    "NotificationSendResponse",
    "BulkNotificationResponse"
]