"""add description to delivery_challan_item

Revision ID: 0e6efa4ed5cd
Revises: 766f74c7f2d6
Create Date: 2025-09-13 14:45:58.161148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e6efa4ed5cd'
down_revision = '766f74c7f2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_challan_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_challan_items', 'description')
    # ### end Alembic commands ###