"""add module action to service_permissions

Revision ID: 0f8fa3f1e5c4
Revises: 2dfc3082482b  # Replace with your latest migration ID
Create Date: 2025-11-08 03:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8fa3f1e5c4'
down_revision = '2dfc3082482b'  # Replace with your latest migration ID
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_permissions', sa.Column('module', sa.String(length=50), nullable=True))
    op.add_column('service_permissions', sa.Column('action', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_permissions', 'action')
    op.drop_column('service_permissions', 'module')
    # ### end Alembic commands ###