# migrations/versions/1862ae9d20c2_add_owner_and_industry_to_leads.py

"""add owner and industry to leads
Revision ID: 1862ae9d20c2
Revises: 825c29e91e03
Create Date: 2025-12-02 13:52:41.367376
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '1862ae9d20c2'
down_revision = '825c29e91e03'
branch_labels = None
depends_on = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('owner', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'industry')
    op.drop_column('leads', 'owner')
    # ### end Alembic commands ###