"""Fix relationship paths in presales

Revision ID: 2cd9a7ce3604
Revises: d45ce3c0d82f
Create Date: 2025-09-13 02:21:02.960728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cd9a7ce3604'
down_revision = 'd45ce3c0d82f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('discount_percentage', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('gst_rate', sa.Float(), nullable=False, server_default='18.0'))
    op.add_column('quotation_items', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('taxable_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('cgst_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('sgst_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('igst_amount', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('quotation_items', sa.Column('description', sa.Text(), nullable=True))
    # Removed op.add_column for 'product_id' since it already exists
    # op.add_column('quotation_items', sa.Column('product_id', sa.Integer(), nullable=False))
    # op.create_foreign_key(None, 'quotation_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    # op.drop_column('quotation_items', 'product_id')
    op.drop_column('quotation_items', 'description')
    op.drop_column('quotation_items', 'igst_amount')
    op.drop_column('quotation_items', 'sgst_amount')
    op.drop_column('quotation_items', 'cgst_amount')
    op.drop_column('quotation_items', 'taxable_amount')
    op.drop_column('quotation_items', 'discount_amount')
    op.drop_column('quotation_items', 'gst_rate')
    op.drop_column('quotation_items', 'discount_percentage')
    # ### end Alembic commands ###