"""add role_id to users

Revision ID: 2dfc3082482b
Revises: bb1de77828d1
Create Date: 2025-11-08 00:38:27.547855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2dfc3082482b'
down_revision = 'bb1de77828d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_role_key'), 'roles', ['role_key'], unique=True)
    op.create_table('role_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('has_access', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_module_permissions_id'), 'role_module_permissions', ['id'], unique=False)
    op.create_table('permission_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('grant', 'revoke', 'modify', name='permission_action'), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_audits_id'), 'permission_audits', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('permission_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('submodule_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['submodule_id'], ['submodules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_permission_key'), 'permissions', ['permission_key'], unique=True)
    op.create_table('user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('has_access', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_module_permissions_id'), 'user_module_permissions', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_id'), 'user_permissions', ['id'], unique=False)
    op.create_index('idx_audit_org_timestamp', 'audit_logs_enhanced', ['organization_id', 'timestamp'], unique=False)
    op.create_index('idx_integration_org_provider', 'integrations', ['organization_id', 'provider'], unique=False)
    op.create_index('idx_integration_org_status', 'integrations', ['organization_id', 'status'], unique=False)
    op.add_column('service_permissions', sa.Column('permission_key', sa.String(length=100), nullable=True))
    op.execute("UPDATE service_permissions SET permission_key = CONCAT(module, '.', action) WHERE permission_key IS NULL")
    op.alter_column('service_permissions', 'permission_key', nullable=False)
    op.add_column('service_permissions', sa.Column('category', sa.String(length=50), nullable=True))
    op.alter_column('service_permissions', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('service_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('service_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('service_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_service_permission_module', table_name='service_permissions')
    op.drop_index('ix_service_permissions_action', table_name='service_permissions')
    op.drop_index('ix_service_permissions_module', table_name='service_permissions')
    op.drop_index('ix_service_permissions_name', table_name='service_permissions')
    op.drop_constraint('uq_service_permission_module_action', 'service_permissions', type_='unique')
    op.create_index(op.f('ix_service_permissions_permission_key'), 'service_permissions', ['permission_key'], unique=True)
    op.drop_column('service_permissions', 'name')
    op.drop_column('service_permissions', 'module')
    op.drop_column('service_permissions', 'action')
    op.add_column('service_role_permissions', sa.Column('granted_at', sa.DateTime(), nullable=True))
    op.add_column('service_role_permissions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_index('ix_service_role_permissions_permission_id', table_name='service_role_permissions')
    op.drop_index('ix_service_role_permissions_role_id', table_name='service_role_permissions')
    op.drop_constraint('uq_role_permission', 'service_role_permissions', type_='unique')
    op.drop_column('service_role_permissions', 'created_at')
    op.add_column('service_roles', sa.Column('role_key', sa.String(length=50), nullable=True))
    op.execute("UPDATE service_roles SET role_key = name WHERE role_key IS NULL")
    op.alter_column('service_roles', 'role_key', nullable=False)
    op.add_column('service_roles', sa.Column('hierarchy_level', sa.Integer(), nullable=True))
    op.add_column('service_roles', sa.Column('permissions', sa.JSON(), nullable=True))
    op.alter_column('service_roles', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('service_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('service_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('service_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_service_role_org_active', table_name='service_roles')
    op.drop_index('ix_service_roles_name', table_name='service_roles')
    op.drop_index('ix_service_roles_organization_id', table_name='service_roles')
    op.drop_constraint('uq_service_role_org_name', 'service_roles', type_='unique')
    op.create_index(op.f('ix_service_roles_role_key'), 'service_roles', ['role_key'], unique=True)
    op.drop_column('service_roles', 'name')
    op.add_column('user_service_roles', sa.Column('service_role_id', sa.Integer(), nullable=True))
    op.execute("UPDATE user_service_roles SET service_role_id = role_id WHERE service_role_id IS NULL")
    op.alter_column('user_service_roles', 'service_role_id', nullable=False)
    op.add_column('user_service_roles', sa.Column('assigned_at', sa.DateTime(), nullable=True))
    op.add_column('user_service_roles', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.alter_column('user_service_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('idx_user_service_role_active', table_name='user_service_roles')
    op.drop_index('ix_user_service_roles_role_id', table_name='user_service_roles')
    op.drop_index('ix_user_service_roles_user_id', table_name='user_service_roles')
    op.drop_constraint('uq_user_service_role', 'user_service_roles', type_='unique')
    op.drop_constraint('user_service_roles_role_id_fkey', 'user_service_roles', type_='foreignkey')
    op.drop_constraint('user_service_roles_assigned_by_id_fkey', 'user_service_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_service_roles', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(None, 'user_service_roles', 'service_roles', ['service_role_id'], ['id'])
    op.drop_column('user_service_roles', 'updated_at')
    op.drop_column('user_service_roles', 'assigned_by_id')
    op.drop_column('user_service_roles', 'created_at')
    op.drop_column('user_service_roles', 'role_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('user_service_roles', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user_service_roles', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_service_roles', sa.Column('assigned_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_service_roles', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_service_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_service_roles', type_='foreignkey')
    op.create_foreign_key('user_service_roles_assigned_by_id_fkey', 'user_service_roles', 'users', ['assigned_by_id'], ['id'])
    op.create_foreign_key('user_service_roles_role_id_fkey', 'user_service_roles', 'service_roles', ['role_id'], ['id'])
    op.create_unique_constraint('uq_user_service_role', 'user_service_roles', ['user_id', 'role_id'])
    op.create_index('ix_user_service_roles_user_id', 'user_service_roles', ['user_id'], unique=False)
    op.create_index('ix_user_service_roles_role_id', 'user_service_roles', ['role_id'], unique=False)
    op.create_index('idx_user_service_role_active', 'user_service_roles', ['user_id', 'is_active'], unique=False)
    op.alter_column('user_service_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user_service_roles', 'assigned_by')
    op.drop_column('user_service_roles', 'assigned_at')
    op.drop_column('user_service_roles', 'service_role_id')
    op.add_column('service_roles', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_service_roles_role_key'), table_name='service_roles')
    op.create_unique_constraint('uq_service_role_org_name', 'service_roles', ['organization_id', 'name'])
    op.create_index('ix_service_roles_organization_id', 'service_roles', ['organization_id'], unique=False)
    op.create_index('ix_service_roles_name', 'service_roles', ['name'], unique=False)
    op.create_index('idx_service_role_org_active', 'service_roles', ['organization_id', 'is_active'], unique=False)
    op.alter_column('service_roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('service_roles', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('service_roles', 'permissions')
    op.drop_column('service_roles', 'hierarchy_level')
    op.drop_column('service_roles', 'role_key')
    op.add_column('service_role_permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_role_permission', 'service_role_permissions', ['role_id', 'permission_id'])
    op.create_index('ix_service_role_permissions_role_id', 'service_role_permissions', ['role_id'], unique=False)
    op.create_index('ix_service_role_permissions_permission_id', 'service_role_permissions', ['permission_id'], unique=False)
    op.drop_column('service_role_permissions', 'is_active')
    op.drop_column('service_role_permissions', 'granted_at')
    op.add_column('service_permissions', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('service_permissions', sa.Column('module', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('service_permissions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_service_permissions_permission_key'), table_name='service_permissions')
    op.create_unique_constraint('uq_service_permission_module_action', 'service_permissions', ['module', 'action'])
    op.create_index('ix_service_permissions_name', 'service_permissions', ['name'], unique=True)
    op.create_index('ix_service_permissions_module', 'service_permissions', ['module'], unique=False)
    op.create_index('ix_service_permissions_action', 'service_permissions', ['action'], unique=False)
    op.create_index('idx_service_permission_module', 'service_permissions', ['module'], unique=False)
    op.alter_column('service_permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_permissions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('service_permissions', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('service_permissions', 'category')
    op.drop_column('service_permissions', 'permission_key')
    op.drop_index('idx_integration_org_status', table_name='integrations')
    op.drop_index('idx_integration_org_provider', table_name='integrations')
    op.drop_index('idx_audit_org_timestamp', table_name='audit_logs_enhanced')
    op.drop_index(op.f('ix_user_permissions_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_user_module_permissions_id'), table_name='user_module_permissions')
    op.drop_table('user_module_permissions')
    op.drop_index(op.f('ix_permissions_permission_key'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_permission_audits_id'), table_name='permission_audits')
    op.drop_table('permission_audits')
    op.drop_index(op.f('ix_role_module_permissions_id'), table_name='role_module_permissions')
    op.drop_table('role_module_permissions')
    op.drop_index(op.f('ix_roles_role_key'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###