"""add_additional_charges.py

Revision ID: 321e6d5d5137
Revises: 22038f457955
Create Date: 2025-10-02 14:46:12.541807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '321e6d5d5137'
down_revision = '22038f457955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sticky_notes_id', table_name='sticky_notes')
    op.drop_index('ix_sticky_notes_organization_id', table_name='sticky_notes')
    op.drop_index('ix_sticky_notes_user_id', table_name='sticky_notes')
    op.drop_table('sticky_notes')
    op.add_column('calendar_events', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_calendar_events_external_id'), 'calendar_events', ['external_id'], unique=False)
    op.add_column('goods_receipt_notes', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('proforma_invoices', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('purchase_orders', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('purchase_returns', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('purchase_vouchers', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('quotations', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_orders', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_returns', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sales_vouchers', sa.Column('additional_charges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_snappymail_config_email', 'snappymail_configs', ['email'], unique=False)
    op.add_column('tasks', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tasks_external_id'), 'tasks', ['external_id'], unique=False)
    op.drop_column('user_email_tokens', 'last_history_id')
    op.drop_column('user_email_tokens', 'last_delta_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_tokens', sa.Column('last_delta_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_email_tokens', sa.Column('last_history_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tasks_external_id'), table_name='tasks')
    op.drop_column('tasks', 'external_id')
    op.drop_index('idx_snappymail_config_email', table_name='snappymail_configs')
    op.drop_column('sales_vouchers', 'additional_charges')
    op.drop_column('sales_returns', 'additional_charges')
    op.drop_column('sales_orders', 'additional_charges')
    op.drop_column('quotations', 'additional_charges')
    op.drop_column('purchase_vouchers', 'additional_charges')
    op.drop_column('purchase_returns', 'additional_charges')
    op.drop_column('purchase_orders', 'additional_charges')
    op.drop_column('proforma_invoices', 'additional_charges')
    op.drop_column('goods_receipt_notes', 'additional_charges')
    op.drop_index(op.f('ix_calendar_events_external_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'external_id')
    op.create_table('sticky_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('position', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='fk_sticky_note_organization_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_sticky_note_user_id'),
    sa.PrimaryKeyConstraint('id', name='sticky_notes_pkey')
    )
    op.create_index('ix_sticky_notes_user_id', 'sticky_notes', ['user_id'], unique=False)
    op.create_index('ix_sticky_notes_organization_id', 'sticky_notes', ['organization_id'], unique=False)
    op.create_index('ix_sticky_notes_id', 'sticky_notes', ['id'], unique=False)
    # ### end Alembic commands ###