"""manufacturing modulw refactoring

Revision ID: 397921ab8123
Revises: ebc460e782bc
Create Date: 2025-10-12 09:32:22.572107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397921ab8123'
down_revision = 'ebc460e782bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_workflow_instance_org_status', 'workflow_instances_automation', ['organization_id', 'status'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_instance_org_status', table_name='workflow_instances_automation', if_exists=True)
    # ### end Alembic commands ###