"""add grn_id to purchase_returns

Revision ID: 3acc3b77c756
Revises: b50be8f3da0e
Create Date: 2025-11-25 20:43:40.841524

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3acc3b77c756'
down_revision = 'b50be8f3da0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_returns', sa.Column('grn_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_returns', 'goods_receipt_notes', ['grn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_returns', type_='foreignkey')
    op.drop_column('purchase_returns', 'grn_id')
    # ### end Alembic commands ###