"""yyyy_make_unit_price_total_amount_nullable_delivery_challan_item

Revision ID: 3bc2f13cdd2f
Revises: 0e6efa4ed5cd
Create Date: 2025-09-13 14:52:48.149133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3bc2f13cdd2f'
down_revision = '0e6efa4ed5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_challan_items', 'unit_price',
               existing_type=sa.Float(),
               nullable=True)
    op.alter_column('delivery_challan_items', 'total_amount',
               existing_type=sa.Float(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('delivery_challan_items', 'total_amount',
               existing_type=sa.Float(),
               nullable=False)
    op.alter_column('delivery_challan_items', 'unit_price',
               existing_type=sa.Float(),
               nullable=False)
    # ### end Alembic commands ###