"""add manufacturing features

Revision ID: 3c094925f6a4
Revises: 3acc3b77c756
Create Date: 2025-11-27 14:42:48.575147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c094925f6a4'
down_revision = '3acc3b77c756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('amc_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_organization_id'), 'machines', ['organization_id'], unique=False)
    op.create_table('qc_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('inspector', sa.String(), nullable=False),
    sa.Column('test_results', sa.Text(), nullable=False),
    sa.Column('overall_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_inspections_id'), 'qc_inspections', ['id'], unique=False)
    op.create_index(op.f('ix_qc_inspections_organization_id'), 'qc_inspections', ['organization_id'], unique=False)
    op.create_table('breakdown_maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('breakdown_type', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('time_to_fix', sa.Float(), nullable=True),
    sa.Column('spare_parts_used', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('downtime_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breakdown_maintenances_id'), 'breakdown_maintenances', ['id'], unique=False)
    op.create_index(op.f('ix_breakdown_maintenances_organization_id'), 'breakdown_maintenances', ['organization_id'], unique=False)
    op.create_table('machine_performance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('runtime_hours', sa.Float(), nullable=True),
    sa.Column('idle_hours', sa.Float(), nullable=True),
    sa.Column('efficiency_percentage', sa.Float(), nullable=True),
    sa.Column('error_codes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machine_performance_logs_id'), 'machine_performance_logs', ['id'], unique=False)
    op.create_index(op.f('ix_machine_performance_logs_organization_id'), 'machine_performance_logs', ['organization_id'], unique=False)
    op.create_table('preventive_maintenance_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.Column('tasks', sa.Text(), nullable=False),
    sa.Column('assigned_technician', sa.String(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overdue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preventive_maintenance_schedules_id'), 'preventive_maintenance_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_preventive_maintenance_schedules_organization_id'), 'preventive_maintenance_schedules', ['organization_id'], unique=False)
    op.create_table('rejections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('qc_inspection_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rework_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['qc_inspection_id'], ['qc_inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejections_id'), 'rejections', ['id'], unique=False)
    op.create_index(op.f('ix_rejections_organization_id'), 'rejections', ['organization_id'], unique=False)
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('min_level', sa.Float(), nullable=True),
    sa.Column('reorder_level', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_spare_parts_id'), 'spare_parts', ['id'], unique=False)
    op.create_index(op.f('ix_spare_parts_organization_id'), 'spare_parts', ['organization_id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('old_quantity', sa.Float(), nullable=False),
    sa.Column('new_quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_adjustments_id'), 'inventory_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_organization_id'), 'inventory_adjustments', ['organization_id'], unique=False)
    op.create_table('qc_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('tolerance_min', sa.Float(), nullable=True),
    sa.Column('tolerance_max', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_templates_id'), 'qc_templates', ['id'], unique=False)
    op.create_index(op.f('ix_qc_templates_organization_id'), 'qc_templates', ['organization_id'], unique=False)
    op.add_column('manufacturing_orders', sa.Column('shift', sa.String(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('wastage_percentage', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('time_taken', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('power_consumption', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('downtime_events', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_pr_org_grn', 'purchase_returns', ['organization_id', 'grn_id'])
    op.create_unique_constraint('uq_pv_org_grn', 'purchase_vouchers', ['organization_id', 'grn_id'])
    op.drop_column('service_roles', 'permissions')
    op.add_column('user_service_roles', sa.Column('assigned_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_service_roles_assigned_by_fkey', 'user_service_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_service_roles', 'users', ['assigned_by_id'], ['id'])
    op.drop_column('user_service_roles', 'assigned_by')
    # op.create_index('idx_workflow_instance_org_status', 'workflow_instances_automation', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_instance_org_status', table_name='workflow_instances_automation')
    op.add_column('user_service_roles', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_service_roles', type_='foreignkey')
    op.create_foreign_key('user_service_roles_assigned_by_fkey', 'user_service_roles', 'users', ['assigned_by'], ['id'])
    op.drop_column('user_service_roles', 'assigned_by_id')
    op.add_column('service_roles', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_pv_org_grn', 'purchase_vouchers', type_='unique')
    op.drop_constraint('uq_pr_org_grn', 'purchase_returns', type_='unique')
    op.drop_column('manufacturing_orders', 'downtime_events')
    op.drop_column('manufacturing_orders', 'power_consumption')
    op.drop_column('manufacturing_orders', 'time_taken')
    op.drop_column('manufacturing_orders', 'wastage_percentage')
    op.drop_column('manufacturing_orders', 'shift')
    op.drop_index(op.f('ix_qc_templates_organization_id'), table_name='qc_templates')
    op.drop_index(op.f('ix_qc_templates_id'), table_name='qc_templates')
    op.drop_table('qc_templates')
    op.drop_index(op.f('ix_inventory_adjustments_organization_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_spare_parts_organization_id'), table_name='spare_parts')
    op.drop_index(op.f('ix_spare_parts_id'), table_name='spare_parts')
    op.drop_table('spare_parts')
    op.drop_index(op.f('ix_rejections_organization_id'), table_name='rejections')
    op.drop_index(op.f('ix_rejections_id'), table_name='rejections')
    op.drop_table('rejections')
    op.drop_index(op.f('ix_preventive_maintenance_schedules_organization_id'), table_name='preventive_maintenance_schedules')
    op.drop_index(op.f('ix_preventive_maintenance_schedules_id'), table_name='preventive_maintenance_schedules')
    op.drop_table('preventive_maintenance_schedules')
    op.drop_index(op.f('ix_machine_performance_logs_organization_id'), table_name='machine_performance_logs')
    op.drop_index(op.f('ix_machine_performance_logs_id'), table_name='machine_performance_logs')
    op.drop_table('machine_performance_logs')
    op.drop_index(op.f('ix_breakdown_maintenances_organization_id'), table_name='breakdown_maintenances')
    op.drop_index(op.f('ix_breakdown_maintenances_id'), table_name='breakdown_maintenances')
    op.drop_table('breakdown_maintenances')
    op.drop_index(op.f('ix_qc_inspections_organization_id'), table_name='qc_inspections')
    op.drop_index(op.f('ix_qc_inspections_id'), table_name='qc_inspections')
    op.drop_table('qc_inspections')
    op.drop_index(op.f('ix_machines_organization_id'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    # ### end Alembic commands ###