"""add tax columns to po items

Revision ID: 42a26066507b
Revises: 6463473f959b
Create Date: 2025-09-05 01:30:33.385744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a26066507b'
down_revision = '6463473f959b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_journal_org_date', 'journal_vouchers', ['organization_id', 'date'], unique=False)
    op.add_column('purchase_order_items', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('gst_rate', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('taxable_amount', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('cgst_amount', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('sgst_amount', sa.Float(), nullable=True))
    op.add_column('purchase_order_items', sa.Column('igst_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'igst_amount')
    op.drop_column('purchase_order_items', 'sgst_amount')
    op.drop_column('purchase_order_items', 'cgst_amount')
    op.drop_column('purchase_order_items', 'taxable_amount')
    op.drop_column('purchase_order_items', 'discount_amount')
    op.drop_column('purchase_order_items', 'gst_rate')
    op.drop_column('purchase_order_items', 'discount_percentage')
    op.drop_index('idx_journal_org_date', table_name='journal_vouchers')
    # ### end Alembic commands ###