"""fix_fk_to_users

Revision ID: 4900389cc5c0
Revises: 538365d334d1
Create Date: 2025-09-22 10:58:45.472246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4900389cc5c0'
down_revision = '538365d334d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_reconciliations_created_by_fkey', 'bank_reconciliations', type_='foreignkey')
    op.create_foreign_key(None, 'bank_reconciliations', 'users', ['created_by'], ['id'])
    op.drop_constraint('chart_of_accounts_updated_by_fkey', 'chart_of_accounts', type_='foreignkey')
    op.drop_constraint('chart_of_accounts_created_by_fkey', 'chart_of_accounts', type_='foreignkey')
    op.create_foreign_key(None, 'chart_of_accounts', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'chart_of_accounts', 'users', ['updated_by'], ['id'])
    op.alter_column('contra_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_contra_vouchers_chart_account_id'), 'contra_vouchers', ['chart_account_id'], unique=False)
    op.drop_constraint('cost_centers_manager_id_fkey', 'cost_centers', type_='foreignkey')
    op.drop_constraint('cost_centers_created_by_fkey', 'cost_centers', type_='foreignkey')
    op.create_foreign_key(None, 'cost_centers', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'cost_centers', 'users', ['manager_id'], ['id'])
    op.drop_constraint('financial_kpis_calculated_by_fkey', 'financial_kpis', type_='foreignkey')
    op.create_foreign_key(None, 'financial_kpis', 'users', ['calculated_by'], ['id'])
    op.drop_constraint('financial_statements_generated_by_fkey', 'financial_statements', type_='foreignkey')
    op.create_foreign_key(None, 'financial_statements', 'users', ['generated_by'], ['id'])
    op.drop_constraint('general_ledger_created_by_fkey', 'general_ledger', type_='foreignkey')
    op.create_foreign_key(None, 'general_ledger', 'users', ['created_by'], ['id'])
    op.drop_constraint('journal_entries_created_by_fkey', 'journal_entries', type_='foreignkey')
    op.create_foreign_key(None, 'journal_entries', 'users', ['created_by'], ['id'])
    op.alter_column('journal_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_journal_vouchers_chart_account_id'), 'journal_vouchers', ['chart_account_id'], unique=False)
    op.drop_constraint('payment_records_created_by_fkey', 'payment_records', type_='foreignkey')
    op.create_foreign_key(None, 'payment_records', 'users', ['created_by'], ['id'])
    op.alter_column('payment_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_payment_vouchers_chart_account_id'), 'payment_vouchers', ['chart_account_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_chart_account_id'), 'payroll_lines', ['chart_account_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_component_id'), 'payroll_lines', ['component_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_employee_id'), 'payroll_lines', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_lines_payroll_run_id'), 'payroll_lines', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_period_id'), 'payroll_runs', ['period_id'], unique=False)
    # Comment out these lines as the index already exists
    # op.drop_index('idx_purchase_returns_org_date', table_name='purchase_returns')
    # op.create_index('idx_pr_org_date', 'purchase_returns', ['organization_id', 'date'], unique=False)
    op.alter_column('receipt_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_receipt_vouchers_chart_account_id'), 'receipt_vouchers', ['chart_account_id'], unique=False)
    op.alter_column('voucher_approvals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_workflow_instance_auto_org_status', table_name='workflow_instances_automation')
    op.create_index('idx_workflow_instance_org_status', 'workflow_instances_automation', ['organization_id', 'status'], unique=False)
    op.drop_index('idx_workflow_template_adv_org_category', table_name='workflow_templates_advanced')
    op.create_index('idx_workflow_template_org_category', 'workflow_templates_advanced', ['organization_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_template_org_category', table_name='workflow_templates_advanced')
    op.create_index('idx_workflow_template_adv_org_category', 'workflow_templates_advanced', ['organization_id', 'category'], unique=False)
    op.drop_index('idx_workflow_instance_org_status', table_name='workflow_instances_automation')
    op.create_index('idx_workflow_instance_auto_org_status', 'workflow_instances_automation', ['organization_id', 'status'], unique=False)
    op.alter_column('voucher_approvals', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_receipt_vouchers_chart_account_id'), table_name='receipt_vouchers')
    op.alter_column('receipt_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # Comment out these lines for consistency
    # op.drop_index('idx_pr_org_date', table_name='purchase_returns')
    # op.create_index('idx_purchase_returns_org_date', 'purchase_returns', ['organization_id', 'date'], unique=False)
    op.drop_index(op.f('ix_payroll_runs_period_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_lines_payroll_run_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_employee_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_component_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payroll_lines_chart_account_id'), table_name='payroll_lines')
    op.drop_index(op.f('ix_payment_vouchers_chart_account_id'), table_name='payment_vouchers')
    op.alter_column('payment_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'payment_records', type_='foreignkey')
    op.create_foreign_key('payment_records_created_by_fkey', 'payment_records', 'platform_users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_journal_vouchers_chart_account_id'), table_name='journal_vouchers')
    op.alter_column('journal_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.create_foreign_key('journal_entries_created_by_fkey', 'journal_entries', 'platform_users', ['created_by'], ['id'])
    op.drop_constraint(None, 'general_ledger', type_='foreignkey')
    op.create_foreign_key('general_ledger_created_by_fkey', 'general_ledger', 'platform_users', ['created_by'], ['id'])
    op.drop_constraint(None, 'financial_statements', type_='foreignkey')
    op.create_foreign_key('financial_statements_generated_by_fkey', 'financial_statements', 'platform_users', ['generated_by'], ['id'])
    op.drop_constraint(None, 'financial_kpis', type_='foreignkey')
    op.create_foreign_key('financial_kpis_calculated_by_fkey', 'financial_kpis', 'platform_users', ['calculated_by'], ['id'])
    op.drop_constraint(None, 'cost_centers', type_='foreignkey')
    op.drop_constraint(None, 'cost_centers', type_='foreignkey')
    op.create_foreign_key('cost_centers_created_by_fkey', 'cost_centers', 'platform_users', ['created_by'], ['id'])
    op.create_foreign_key('cost_centers_manager_id_fkey', 'cost_centers', 'platform_users', ['manager_id'], ['id'])
    op.drop_index(op.f('ix_contra_vouchers_chart_account_id'), table_name='contra_vouchers')
    op.alter_column('contra_vouchers', 'chart_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'chart_of_accounts', type_='foreignkey')
    op.drop_constraint(None, 'chart_of_accounts', type_='foreignkey')
    op.create_foreign_key('chart_of_accounts_created_by_fkey', 'chart_of_accounts', 'platform_users', ['created_by'], ['id'])
    op.create_foreign_key('chart_of_accounts_updated_by_fkey', 'chart_of_accounts', 'platform_users', ['updated_by'], ['id'])
    op.drop_constraint(None, 'bank_reconciliations', type_='foreignkey')
    op.create_foreign_key('bank_reconciliations_created_by_fkey', 'bank_reconciliations', 'platform_users', ['created_by'], ['id'])
    # ### end Alembic commands ###