"""add production_order_id to production_entries

Revision ID: 605ab52c9295
Revises: 70ad2d33fc29
Create Date: 2025-11-29 14:02:23.036563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605ab52c9295'
down_revision = '70ad2d33fc29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TABLE IF NOT EXISTS production_entry_consumption ("
               "id SERIAL PRIMARY KEY,"
               "production_entry_id INTEGER NOT NULL,"
               "component_id INTEGER NOT NULL,"
               "actual_qty DOUBLE PRECISION NOT NULL,"
               "wastage_qty DOUBLE PRECISION,"
               "FOREIGN KEY (component_id) REFERENCES products(id),"
               "FOREIGN KEY (production_entry_id) REFERENCES production_entries(id)"
               ")")
    op.execute("CREATE INDEX IF NOT EXISTS ix_production_entry_consumption_id ON production_entry_consumption (id)")
    op.execute("CREATE TABLE IF NOT EXISTS production_entry_consumptions ("
               "id SERIAL PRIMARY KEY,"
               "organization_id INTEGER NOT NULL,"
               "production_entry_id INTEGER NOT NULL,"
               "component_id INTEGER NOT NULL,"
               "actual_qty DOUBLE PRECISION NOT NULL,"
               "wastage_qty DOUBLE PRECISION,"
               "FOREIGN KEY (component_id) REFERENCES products(id),"
               "FOREIGN KEY (organization_id) REFERENCES organizations(id),"
               "FOREIGN KEY (production_entry_id) REFERENCES production_entries(id)"
               ")")
    op.execute("CREATE INDEX IF NOT EXISTS ix_production_entry_consumptions_id ON production_entry_consumptions (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_production_entry_consumptions_organization_id ON production_entry_consumptions (organization_id)")
    op.execute("DROP INDEX IF EXISTS ix_production_entry_items_id")
    op.execute("DROP TABLE IF EXISTS production_entry_items")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_org_timestamp ON audit_logs (organization_id, timestamp)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_integration_org_provider ON external_integrations (organization_id, provider)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_integration_org_status ON external_integrations (organization_id, status)")
    op.execute("ALTER TABLE manufacturing_journal_materials ADD COLUMN IF NOT EXISTS quality_grade VARCHAR")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS production_order_id INTEGER NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS machine VARCHAR")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS batch_number VARCHAR NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS actual_quantity DOUBLE PRECISION NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS time_taken DOUBLE PRECISION NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS labor_hours DOUBLE PRECISION NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS machine_hours DOUBLE PRECISION NOT NULL")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS power_consumption DOUBLE PRECISION")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS downtime_events JSON")
    op.execute("DROP INDEX IF EXISTS idx_pe_org_mo")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pe_org_po ON production_entries (organization_id, production_order_id)")
    op.execute("ALTER TABLE production_entries DROP CONSTRAINT IF EXISTS production_entries_manufacturing_order_id_fkey")
    op.execute("ALTER TABLE production_entries ADD CONSTRAINT production_entries_production_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES manufacturing_orders(id)")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS manufacturing_order_id")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS good_quantity")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS rework_quantity")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS machine_used")
    op.execute("CREATE INDEX IF NOT EXISTS idx_workflow_instance_org_status ON workflow_instances_automation (organization_id, status)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_workflow_instance_org_status")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS machine_used VARCHAR")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS rework_quantity DOUBLE PRECISION")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS good_quantity DOUBLE PRECISION")
    op.execute("ALTER TABLE production_entries ADD COLUMN IF NOT EXISTS manufacturing_order_id INTEGER NOT NULL")
    op.execute("ALTER TABLE production_entries DROP CONSTRAINT IF EXISTS production_entries_production_order_id_fkey")
    op.execute("ALTER TABLE production_entries ADD CONSTRAINT production_entries_manufacturing_order_id_fkey FOREIGN KEY (manufacturing_order_id) REFERENCES manufacturing_orders(id)")
    op.execute("DROP INDEX IF EXISTS idx_pe_org_po")
    op.execute("CREATE INDEX IF NOT EXISTS idx_pe_org_mo ON production_entries (organization_id, manufacturing_order_id)")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS downtime_events")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS power_consumption")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS machine_hours")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS labor_hours")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS time_taken")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS actual_quantity")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS batch_number")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS machine")
    op.execute("ALTER TABLE production_entries DROP COLUMN IF EXISTS production_order_id")
    op.execute("ALTER TABLE manufacturing_journal_materials DROP COLUMN IF EXISTS quality_grade")
    op.execute("DROP INDEX IF EXISTS idx_integration_org_status")
    op.execute("DROP INDEX IF EXISTS idx_integration_org_provider")
    op.execute("DROP INDEX IF EXISTS idx_audit_org_timestamp")
    op.execute("CREATE TABLE IF NOT EXISTS production_entry_items ("
               "production_entry_id INTEGER NOT NULL,"
               "id SERIAL PRIMARY KEY,"
               "product_id INTEGER NOT NULL,"
               "quantity DOUBLE PRECISION NOT NULL,"
               "unit VARCHAR NOT NULL,"
               "unit_price DOUBLE PRECISION NOT NULL,"
               "discount_percentage DOUBLE PRECISION,"
               "discount_amount DOUBLE PRECISION,"
               "taxable_amount DOUBLE PRECISION NOT NULL,"
               "gst_rate DOUBLE PRECISION,"
               "cgst_amount DOUBLE PRECISION,"
               "sgst_amount DOUBLE PRECISION,"
               "igst_amount DOUBLE PRECISION,"
               "total_amount DOUBLE PRECISION NOT NULL,"
               "FOREIGN KEY (product_id) REFERENCES products(id),"
               "FOREIGN KEY (production_entry_id) REFERENCES production_entries(id)"
               ")")
    op.execute("CREATE INDEX IF NOT EXISTS ix_production_entry_items_id ON production_entry_items (id)")
    op.execute("DROP INDEX IF EXISTS ix_production_entry_consumptions_organization_id")
    op.execute("DROP INDEX IF EXISTS ix_production_entry_consumptions_id")
    op.execute("DROP TABLE IF EXISTS production_entry_consumptions")
    op.execute("DROP INDEX IF EXISTS ix_production_entry_consumption_id")
    op.execute("DROP TABLE IF EXISTS production_entry_consumption")
    # ### end Alembic commands ###