"""Rename product name to product_name

Revision ID: 6463473f959b
Revises: 3dcc06f2ad14
Create Date: 2025-09-03 22:06:25.802336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6463473f959b'
down_revision = '3dcc06f2ad14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index('idx_journal_org_date', 'journal_vouchers', ['organization_id', 'date'], unique=False)
    op.drop_index('idx_user_org_username', table_name='users')
    op.drop_constraint('uq_user_org_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_user_org_username', 'users', ['organization_id', 'username'])
    op.create_index('idx_user_org_username', 'users', ['organization_id', 'username'], unique=False)
    op.drop_index('idx_journal_org_date', table_name='journal_vouchers')
    # ### end Alembic commands ###