"""add round_off to purchase_orders

Revision ID: 649c2623e6c7
Revises: 9803e9064995
Create Date: 2025-09-10 08:16:30.468425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '649c2623e6c7'
down_revision = '9803e9064995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('round_off', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'round_off')
    # ### end Alembic commands ###