"""add bank and cash to account_type enum

Revision ID: 76016d4a23bc
Revises: 447e4092b5d5
Create Date: 2025-09-21 11:39:28.186800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76016d4a23bc'
down_revision = '447e4092b5d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE accounttype ADD VALUE 'bank'")
    op.execute("ALTER TYPE accounttype ADD VALUE 'cash'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###