"""add fields to sales_order_items

Revision ID: 766f74c7f2d6
Revises: 83d1bb4503df  # Assuming this is the previous revision; adjust if needed
Create Date: 2025-09-13 10:00:00.000000  # Adjust date as needed

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '766f74c7f2d6'
down_revision = '83d1bb4503df'  # Replace with actual previous revision if different
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_order_items', sa.Column('discount_percentage', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('gst_rate', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('discount_amount', sa.Float(), nullable=False))
    op.add_column('sales_order_items', sa.Column('taxable_amount', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('cgst_amount', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('sgst_amount', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('igst_amount', sa.Float(), nullable=True))
    op.add_column('sales_order_items', sa.Column('description', sa.Text(), nullable=True))
    # Set default values for new columns if needed (optional, but helps with existing data)
    op.execute("UPDATE sales_order_items SET discount_percentage = 0.0 WHERE discount_percentage IS NULL")
    op.execute("UPDATE sales_order_items SET gst_rate = 18.0 WHERE gst_rate IS NULL")
    op.execute("UPDATE sales_order_items SET discount_amount = 0.0 WHERE discount_amount IS NULL")
    op.execute("UPDATE sales_order_items SET taxable_amount = 0.0 WHERE taxable_amount IS NULL")
    op.execute("UPDATE sales_order_items SET cgst_amount = 0.0 WHERE cgst_amount IS NULL")
    op.execute("UPDATE sales_order_items SET sgst_amount = 0.0 WHERE sgst_amount IS NULL")
    op.execute("UPDATE sales_order_items SET igst_amount = 0.0 WHERE igst_amount IS NULL")
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_order_items', 'description')
    op.drop_column('sales_order_items', 'igst_amount')
    op.drop_column('sales_order_items', 'sgst_amount')
    op.drop_column('sales_order_items', 'cgst_amount')
    op.drop_column('sales_order_items', 'taxable_amount')
    op.drop_column('sales_order_items', 'discount_amount')
    op.drop_column('sales_order_items', 'gst_rate')
    op.drop_column('sales_order_items', 'discount_percentage')
    # ### end Alembic commands ###