"""add description to purchase_voucher_items

Revision ID: b50be8f3da0e
Revises: 3fba9cac4b29
Create Date: 2025-11-25 19:51:45.124607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50be8f3da0e'
down_revision = '3fba9cac4b29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_voucher_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_voucher_items', 'description')
    # ### end Alembic commands ###