"""20250917_055924_add_description_to_proforma_invoice_items

Revision ID: c69275b0b978
Revises: caab765e48ad
Create Date: 2025-09-17 11:31:58.559870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c69275b0b978'
down_revision = 'caab765e48ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma_invoice_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma_invoice_items', 'description')
    # ### end Alembic commands ###