"""add tally config to organization_settings

Revision ID: c786278d3775
Revises: c426d9540823  # Adjust if needed to previous revision ID
Create Date: 2025-10-15  # Adjust date if needed

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c786278d3775'
down_revision = 'c426d9540823'  # Adjust to previous revision
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('tally_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organization_settings', sa.Column('tally_host', sa.String(), nullable=True))
    op.add_column('organization_settings', sa.Column('tally_port', sa.Integer(), nullable=True))
    op.add_column('organization_settings', sa.Column('tally_username', sa.String(), nullable=True))
    op.add_column('organization_settings', sa.Column('tally_password', sa.String(), nullable=True))
    # Add other Tally config columns if any, based on model
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'tally_password')
    op.drop_column('organization_settings', 'tally_username')
    op.drop_column('organization_settings', 'tally_port')
    op.drop_column('organization_settings', 'tally_host')
    op.drop_column('organization_settings', 'tally_enabled')
    # ### end Alembic commands ###