"""add description to purchase_order_items

Revision ID: d45ce3c0d82f
Revises: add_role_approval_workflow
Create Date: 2025-09-11 23:30:13.171312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd45ce3c0d82f'
down_revision = 'add_role_approval_workflow'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_items', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_items', 'description')
    # ### end Alembic commands ###