"""fix_email_enums.py

Revision ID: e63da1a343bc
Revises: f178178734f5
Create Date: 2025-10-11 01:06:24.099506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e63da1a343bc'
down_revision = 'f178178734f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create new enum for email message status
    op.execute("CREATE TYPE email_message_status AS ENUM ('UNREAD', 'READ', 'REPLIED', 'FORWARDED', 'ARCHIVED', 'DELETED', 'SPAM')")
    
    # Alter emails.status to use new enum (cast since values are compatible if table empty)
    op.execute("ALTER TABLE emails ALTER COLUMN status TYPE email_message_status USING status::text::email_message_status")
    
    # Rename existing emailstatus to email_schedule_status (assuming it's for scheduled_emails)
    op.execute("ALTER TYPE emailstatus RENAME TO email_schedule_status")
    
    # Create enum for email priority if not exists
    op.execute("CREATE TYPE email_priority AS ENUM ('LOW', 'NORMAL', 'HIGH', 'URGENT')")
    
    # Alter emails.priority to use it
    op.execute("ALTER TABLE emails ALTER COLUMN priority TYPE email_priority USING priority::text::email_priority")
    
    # Do same for email_threads.status and .priority
    op.execute("ALTER TABLE email_threads ALTER COLUMN status TYPE email_message_status USING status::text::email_message_status")
    op.execute("ALTER TABLE email_threads ALTER COLUMN priority TYPE email_priority USING priority::text::email_priority")
    
    # For scheduled_emails.status, ensure it's using email_schedule_status
    op.execute("ALTER TABLE scheduled_emails ALTER COLUMN status TYPE email_schedule_status USING status::text::email_schedule_status")
    
    # For email_sync_logs.status, assume it's varchar, no change
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse alterations
    op.execute("ALTER TABLE emails ALTER COLUMN status TYPE email_schedule_status USING status::text::email_schedule_status")
    op.execute("ALTER TABLE email_threads ALTER COLUMN status TYPE email_schedule_status USING status::text::email_schedule_status")
    
    op.execute("DROP TYPE email_message_status")
    op.execute("DROP TYPE email_priority")
    
    op.execute("ALTER TYPE email_schedule_status RENAME TO emailstatus")
    # ### end Alembic commands ###