"""add manufacturing order fields

Revision ID: ebc460e782bc
Revises: e63da1a343bc
Create Date: 2025-10-12 00:24:04.155939

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebc460e782bc'
down_revision = 'e63da1a343bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_sends', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'RETRY', 'DELIVERED', 'BOUNCED', name='email_schedule_status'),
               type_=sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRY', 'DELIVERED', 'BOUNCED', name='emailstatus'),
               existing_nullable=False,
               postgresql_using="status::text::emailstatus")
    op.create_index(op.f('ix_email_threads_status'), 'email_threads', ['status'], unique=False)
    op.drop_index('idx_email_from_received', table_name='emails')
    op.create_index('idx_email_org_from_received', 'emails', ['organization_id', 'from_address', 'received_at'], unique=False)
    op.alter_column('inventory_alerts', 'alert_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'SHORTAGE_FOR_MO', 'OVERSTOCK', 'EXPIRY_ALERT', name='alerttype'),
               existing_nullable=False,
               postgresql_using="alert_type::text::alerttype")
    op.alter_column('inventory_alerts', 'current_stock',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_alerts', 'reorder_level',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=False)
    op.alter_column('inventory_alerts', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ACTIVE', 'RESOLVED', 'DISMISSED', name='alertstatus'),
               existing_nullable=False,
               postgresql_using="status::text::alertstatus")
    op.alter_column('inventory_alerts', 'priority',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'),
               existing_nullable=False,
               postgresql_using="priority::text::alertpriority")
    op.alter_column('inventory_alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('inventory_alerts', 'suggested_order_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=3),
               existing_nullable=True)
    op.alter_column('inventory_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index('idx_alert_org_type_status', 'inventory_alerts', ['organization_id', 'alert_type', 'status'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_alert_type'), 'inventory_alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_product_id'), 'inventory_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_alerts_status'), 'inventory_alerts', ['status'], unique=False)
    op.add_column('manufacturing_orders', sa.Column('assigned_operator', sa.String(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('assigned_supervisor', sa.String(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('machine_id', sa.String(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('workstation_id', sa.String(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('estimated_labor_hours', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('actual_labor_hours', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('estimated_setup_time', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('estimated_run_time', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('actual_setup_time', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('actual_run_time', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('completion_percentage', sa.Float(), nullable=True))
    op.add_column('manufacturing_orders', sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_workflow_inst_auto_org_status', table_name='workflow_instances_automation')
    op.execute("CREATE INDEX IF NOT EXISTS idx_workflow_instance_org_status ON workflow_instances_automation (organization_id, status)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_workflow_instance_org_status")
    op.create_index('idx_workflow_inst_auto_org_status', 'workflow_instances_automation', ['organization_id', 'status'], unique=False)
    op.drop_column('manufacturing_orders', 'last_updated_at')
    op.drop_column('manufacturing_orders', 'completion_percentage')
    op.drop_column('manufacturing_orders', 'actual_run_time')
    op.drop_column('manufacturing_orders', 'actual_setup_time')
    op.drop_column('manufacturing_orders', 'estimated_run_time')
    op.drop_column('manufacturing_orders', 'estimated_setup_time')
    op.drop_column('manufacturing_orders', 'actual_labor_hours')
    op.drop_column('manufacturing_orders', 'estimated_labor_hours')
    op.drop_column('manufacturing_orders', 'workstation_id')
    op.drop_column('manufacturing_orders', 'machine_id')
    op.drop_column('manufacturing_orders', 'assigned_supervisor')
    op.drop_column('manufacturing_orders', 'assigned_operator')
    op.drop_index(op.f('ix_inventory_alerts_status'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_product_id'), table_name='inventory_alerts')
    op.drop_index(op.f('ix_inventory_alerts_alert_type'), table_name='inventory_alerts')
    op.drop_index('idx_alert_org_type_status', table_name='inventory_alerts')
    op.alter_column('inventory_alerts', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('inventory_alerts', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_alerts', 'suggested_order_quantity',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('inventory_alerts', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_alerts', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertpriority'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="priority::text")
    op.alter_column('inventory_alerts', 'status',
               existing_type=sa.Enum('ACTIVE', 'RESOLVED', 'DISMISSED', name='alertstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="status::text")
    op.alter_column('inventory_alerts', 'reorder_level',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('inventory_alerts', 'current_stock',
               existing_type=sa.Numeric(precision=12, scale=3),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('inventory_alerts', 'alert_type',
               existing_type=sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'SHORTAGE_FOR_MO', 'OVERSTOCK', 'EXPIRY_ALERT', name='alerttype'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="alert_type::text")
    op.drop_index('idx_email_org_from_received', table_name='emails')
    op.create_index('idx_email_from_received', 'emails', ['from_address', 'received_at'], unique=False)
    op.drop_index(op.f('ix_email_threads_status'), table_name='email_threads')
    op.alter_column('email_sends', 'status',
               existing_type=sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRY', 'DELIVERED', 'BOUNCED', name='emailstatus'),
               type_=postgresql.ENUM('PENDING', 'SENT', 'FAILED', 'RETRY', 'DELIVERED', 'BOUNCED', name='email_schedule_status'),
               existing_nullable=False,
               postgresql_using="status::text::email_schedule_status")
    # ### end Alembic commands ###