"""add revision fields to quotation and proforma_invoice

Revision ID: ed74844eaf5a
Revises: 9519442f824d  # Adjust if your previous revision ID differs
Create Date: 2025-09-16 00:00:00.000000  # Adjust date if needed

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed74844eaf5a'
down_revision = '9519442f824d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma_invoices', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('proforma_invoices', sa.Column('revision_number', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'proforma_invoices', 'proforma_invoices', ['parent_id'], ['id'])
    op.add_column('quotations', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('quotations', sa.Column('revision_number', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'quotations', 'quotations', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotations', type_='foreignkey')
    op.drop_column('quotations', 'revision_number')
    op.drop_column('quotations', 'parent_id')
    op.drop_constraint(None, 'proforma_invoices', type_='foreignkey')
    op.drop_column('proforma_invoices', 'revision_number')
    op.drop_column('proforma_invoices', 'parent_id')
    # ### end Alembic commands ###