"""20251127_add_sales_order_id_to_manufacturing_orders_2.py

Revision ID: f74e5554b7de
Revises: 7a34d9036a9d
Create Date: 2025-11-27 22:13:07.807498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74e5554b7de'
down_revision = '7a34d9036a9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturing_orders', sa.Column('sales_order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'manufacturing_orders', 'sales_orders', ['sales_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manufacturing_orders', type_='foreignkey')
    op.drop_column('manufacturing_orders', 'sales_order_id')
    # ### end Alembic commands ###