"""add is_deleted to contra_voucher

Revision ID: f929c83a1646
Revises: 1617b9684107
Create Date: 2025-12-04 23:25:02.675123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f929c83a1646'
down_revision: Union[str, None] = '1617b9684107'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contra_vouchers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # Add if_not_exists=True to avoid error if index already exists
    op.create_index('idx_audit_org_timestamp', 'audit_logs_enhanced', ['organization_id', 'timestamp'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_org_timestamp', table_name='audit_logs_enhanced')
    op.drop_column('contra_vouchers', 'is_deleted')
    # ### end Alembic commands ###