"""add missing tally fields

Revision ID: [replace with actual ID, e.g., abc123def456]
Revises: c786278d3775
Create Date: 2025-10-15

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add missing tally fields'
down_revision = 'c786278d3775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_settings', sa.Column('tally_company_name', sa.String(length=255), nullable=True))
    op.add_column('organization_settings', sa.Column('tally_sync_frequency', sa.String(length=50), nullable=True))
    op.add_column('organization_settings', sa.Column('tally_last_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_settings', 'tally_last_sync')
    op.drop_column('organization_settings', 'tally_sync_frequency')
    op.drop_column('organization_settings', 'tally_company_name')
    # ### end Alembic commands ###